version: '3.9'
services:
  db:
    image: mysql:8.1
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"

  web:
    build: ./webshop-api
    command: ["bin/rails", "server", "-b", "0.0.0.0", "-p", "3000"]
    volumes:
      - ./webshop-api:/app
      - gem_cache:/usr/local/bundle
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: ${RAILS_ENV}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - db

  frontend:
    build: ./webshop-frontend
    volumes:
      - ./webshop-frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["npm", "run", "dev", "--", "--host"]
    depends_on:
      - web

volumes:
  db_data:
  gem_cache: